name: mpas-jedi-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - basemap
  - bokeh
  - cartopy
  - folium
  - geopandas
  - h5netcdf
  - jupyterlab
  - jupyterlab-myst
  - matplotlib
  - mystmd
  - netCDF4
  - pip
  - plotly
  - s3fs
  - scipy
  - seaborn
  # - uxarray  # for now until releasing vertical cross-sections
  - xarray
  - vim
pip:
  - git+https://github.com/UXARRAY/uxarray@interpolate-cross-section  # remove when you revert uxarray above!